### ISSUE TITLE
Registry is unreachable

### ISSUE THREAD

**Issue by devfishyhub** [NIPE-Solutions/flex-layout-migrator#19]
After cloning when trying to download dependencies using 
`npm ci` 

It would complain about proxy which i have none. 
<img width="1692" alt="image" src="https://github.com/NIPE-Solutions/flex-layout-migrator/assets/75593143/a536854a-d912-4a4a-b9b0-1f262a077fe5">

**Comment by Cylop** [comment]
Hello, I am grateful for your patience. I resolved the issue and it should work now!
